### ISSUE TITLE
Run Configuration - Not Working

### ISSUE THREAD

**Issue by Shackelford-Arden** [JetBrains/intellij-streamdeck-plugin#16]
Greetings!

## Quick notes

- I'm on MacOS Sonoma (14.1)
- IDE: Goland (2023.2.4)

## IDE Settings

![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/7362263/08eeaca3-c3c8-434a-80c7-003fb4c37cdf)

## Stream Deck Settings

![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/7362263/0eded7df-8907-4d0c-b1d6-f51b5db96d6e)

## Issue

Well... it just isn't working :smile:. Initially, I wondered if the multi-project multi-tab setting for MacOS (where each project is a tab within the IDE window) was to blame, so I disabled that and tried again. Still nothing happens.

Other actions outside of Jetbrains products are working, so I know the Stream Deck itself does function on my system. Just seems that maybe the OOTB settings are insufficient for my system... for some reason?

I'm unsure how to best troubleshoot, but if guided, I'm more than happy to troubleshoot in whatever way I can.

Thanks! Looking forward to using this! Actually one of the biggest reasons I picked up a Stream Deck in the first place.

**Comment by beansoft** [comment]
Hello, can you try to install https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin this one and see if it helps? I noticed that Stream Deck has switched their app store to a new one and the plugin version on it is somehow not updated to the latest one. I'll try to update it today.

**Comment by Shackelford-Arden** [comment]
@beansoft Pulling in the updated plugin works! :smile: Thank you!

I'll close this out, but if you need anything else from me, just let me know!
