### ISSUE TITLE
Specific Run Configuration 

### ISSUE THREAD

**Issue by rov-sf** [JetBrains/intellij-streamdeck-plugin#17]
I want to run a specific script with the Run Button. I have multiple run configurations. 
For example:
* Clear cache
* Starting vite
* Get latest database dump
* etc.

It would be nice to trigger them directly and not only the last one.

Thanks for your engagement with this plugin! ❤️

**Comment by beansoft** [comment]
@rov-sf 
> I have multiple run configurations

This can be done using a compound run configuration.

 I've implemented a feature like this, you can specify a run/debug name to run/debug it:

<img width="518" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/11939450/53bfc3b5-7986-4948-8b85-8ec7b1ca9d2a">

If this is what your feature request is, I'll upload the new packages for you to do an EAP test.

**Comment by rov-sf** [comment]
@beansoft this is exactly what i want :)

**Comment by beansoft** [comment]
Install this in IDE from disk:
[com.jetbrains.ide.streamdeck.plugin-2023.3.2.zip](https://github.com/JetBrains/intellij-streamdeck-plugin/files/13820445/com.jetbrains.ide.streamdeck.plugin-2023.3.2.zip)

Unzip and double-click to install it on the Stream Deck desktop:
[com.jetbrains.ide.streamDeckPlugin-for Elgato.zip](https://github.com/JetBrains/intellij-streamdeck-plugin/files/13820460/com.jetbrains.ide.streamDeckPlugin-for.Elgato.zip)

Please help test both. Please note that if no configuration specific, it will run the current configuration.

Welcome to report issues back.

**Comment by rov-sf** [comment]
It works, even if the configuration is located in a folder. I created multiple Stream Deck actions, to see if they work indepenent.

But i think its not good, to run the current configuration, when a name is given. I accidentally run a script, which i don't wanted too (switched all Branches to master) :D 

Thanks for letting me test <3

**Comment by beansoft** [comment]
> But i think its not good, to run the current configuration, when a name is given. I accidentally run a script, which i don't wanted too (switched all Branches to master) :D

Can you provide more detail about this, provide a name but still run the current configuration? Any screenshot is welcome.

**Comment by rov-sf** [comment]
Okay, I think I forgot to save the first time. If I enter the wrong configuration name now, nothing happens (as expected)

**Comment by JackyJetBrains** [comment]
Yeah, got it. I think I should split it into a new run/debug with configuration action to avoid confuse.

**Comment by opack** [comment]
This new version is awesome! It's so great to be able to start a run configuration just with a press of a button! 🤩 I installed it using the aforementioned zip, but when (approximatively) will it be officially released on the Elgato store?

**Comment by beansoft** [comment]
The Elgato store needs some time to approve it.

**Comment by beansoft** [comment]
JetBrains IDE has been updated to version 1.0.3 in Elgato Marketplace 🎉

https://marketplace.elgato.com/product/jetbrains-ide-f20a34c4-8965-4e21-8c6a-2454786d748b
