### ISSUE TITLE
Step Into for debbuging

### ISSUE THREAD

**Issue by williamokano-dh** [JetBrains/intellij-streamdeck-plugin#18]
# Context

For debugging, several actions can be used helping the developer, such as step over, step out, and step in.

The plugin already provides `step over` and `step out` out-of-the-box, but I couldn't find the `step in` actions.

Checked the manifest and I could only find the 2 mentioned steps.

Although it might be possible to implement this using the custom command, would be nice to be able to have this out-of-the-box just like the other ones.

## Notes / Questions
The UUID for the steps (over and out) doesn't [seem to follow an standard](https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/streamdeck-plugin/com.jetbrains.ide.sdPlugin/manifest.json#L75-L97), if I decide to contribute with the plugin to implement the other one, which pattern should I follow?

**Comment by JackyJetBrains** [comment]
@williamokano-dh Thank you so much, pull request is welcomed! The UUID just need to be unique,  and referenced in the source code. You can check https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/streamdeck-plugin/src/actions/step-over-action.ts as an example on how to use it by using the Find Usages inlay hints:

<img width="672" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/141385977/c13e6e8e-fd61-435b-880c-94569db6d615">

**Comment by carlislefox** [comment]
I just got everything set up and was like... oh no, we don't have step in! I've managed to wang it in using the custom action but would definitely appreciate this being added.

**Comment by beansoft** [comment]
Hello,  this issue is fixed. Please try the latest package: https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin

Please remove the old version plugin from the Stream Deck App first to upgrade to the new one.
