### ISSUE TITLE
Doesn't Trigger Action with GoLand 2023.3 RC

### ISSUE THREAD

**Issue by lzrf0cuz** [JetBrains/intellij-streamdeck-plugin#19]
The plugin console shows the command from the Stream Deck being registered, but the IDE doesn't trigger the action.

<img width="936" alt="CleanShot 2023-12-05 at 17 30 03@2x" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/20177103/aa377cfe-f367-4606-831d-c39363ffeddc">

**Version**

```
GoLand 2023.3 RC
Build #GO-233.11799.194, built on November 29, 2023
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
```

**Comment by lzrf0cuz** [comment]
Update GoLand to the latest 2023.3, but it still doesn't work.

```
GoLand 2023.3
Build #GO-233.11799.228, built on December 1, 2023
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
```

**Comment by lzrf0cuz** [comment]
I confirmed that it works. Thanks for fixing it at asap.

**Comment by beansoft** [comment]
Thanks for the test, just in case it may be useful:

Tips for non-supported action such as NextDiff: You can always use the Stream Deck App's built-in action HotKey as a workaround.

![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/11939450/75485582-5c7f-4275-8d8a-7159847e11f5)

**Comment by lzrf0cuz** [comment]
> Thanks for the test, just in case it may be useful:
> 
> Tips for non-supported action such as NextDiff: You can always use the Stream Deck App's built-in action HotKey as a workaround.
> 
> ![image](https://private-user-images.githubusercontent.com/11939450/288505438-75485582-5c7f-4275-8d8a-7159847e11f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTQ4MzUsIm5iZiI6MTcwMTg5NDUzNSwicGF0aCI6Ii8xMTkzOTQ1MC8yODg1MDU0MzgtNzU0ODU1ODItNWM3Zi00Mjc1LThkOGEtNzE1OTg0N2UxMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIwMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTlhY2ZlNDIyYzMzZDFkZTFiNTMzZTRkZTk3M2UwNmM2OWM5NDBiZTE4MTgxMzVhN2E4M2EyZGU2MTBlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OV4q1dQW02BwAfki1cjZZeB5bjErUjyY1sKKWmYF6bQ)

That is precisely what I did before the plugin. And now, if a command ID doesn't work. Thanks again.
