### ISSUE TITLE
Icons not centered in button

### ISSUE THREAD

**Issue by robp-anywhere365** [JetBrains/intellij-streamdeck-plugin#2]
**Intro**
Just installed the awesome plugin for my stream deck. The functionality seems to be working like a charm over here. But a small UI issue occurred and wanted to report it, so it is on the backlog.

**Issue:**
The icons for all the actions are not centered logically. see screenshot:
![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/96519975/b9705d01-01bf-451c-a336-86573dac2201)

Keep up the good work!

**Comment by beansoft** [comment]
@robp-anywhere365 Thank you for your advice! I'll fix it this week.
I noticed you are trying to edit the title by yourself, please click the settings button to toggle title visibility.
<img width="537" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/11939450/45cbab2e-91bd-49e5-a56f-51f620f8fea2">

**Comment by robp-anywhere365** [comment]
Thanks, that looks a bit better yes, but still a bit too much to the top with my screen or application.
![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/96519975/f751ee3b-3c7d-467e-9cb4-c92ba8671171)

**Comment by beansoft** [comment]
@robp-anywhere365 It should be fixed now, please try the new file at: https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin

<img width="452" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/11939450/efa2c702-9bf7-4454-bf8b-126887a97671">

**Comment by robp-anywhere365** [comment]
Thanks, looks good over here!

**Comment by felipealvesgnu** [comment]
@beansoft after trying to reinstall shows this message:
<img width="569" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/798927/e1430445-7051-4cde-9757-a617c94f6cf3">

Any idea how to solve it?

**Comment by RareDevil** [comment]
> @beansoft after trying to reinstall shows this message: <img alt="image" width="569" src="https://user-images.githubusercontent.com/798927/259838692-e1430445-7051-4cde-9757-a617c94f6cf3.png">
> 
> Any idea how to solve it?

![image](https://github.com/JetBrains/intellij-streamdeck-plugin/assets/9973318/371a10b7-868b-46e6-9914-335003b97ec3)
right click to get this menu and uninstall it and then you can reinstall it again

**Comment by annikovk** [comment]
Btw, it could be solved by changing plug-in's version in manifest file on every release
