### ISSUE TITLE
Setting a password only works if host is also set

### ISSUE THREAD

**Issue by g0t4** [JetBrains/intellij-streamdeck-plugin#6]
Steps:
- Setup a password in IDE settings. 
- Enter password into a JetBrain's StreamDeck button config. 
- Button fails
- Set `host: localhost` in button config
- Button works

Host should use its default regardless of password, especially because if passwords seem broken people are less likely to use them!

Given #4 too, it appears that any configuration of what is sent to the IDE requires the host to be set?

Keep up the great work!

**Comment by beansoft** [comment]
Please try the latest version(not released yet) from https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin
