### ISSUE TITLE
Change setting `Action Tip` to per-button

### ISSUE THREAD

**Issue by g0t4** [JetBrains/intellij-streamdeck-plugin#7]
Right now if you edit a button and check the box for `Action Tip` all JetBrains button instances will be updated to show the action name. Is that intended?

I was expecting it to be per button instance. I can understand either approach though, just curious if this is a bug or by design.

**Comment by beansoft** [comment]
Yes, it's now a global option, it's not a bug, but as you said, it'll be better for per-button settings.

**Comment by beansoft** [comment]
@g0t4 Please try the latest version(not released yet) from https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin , it's now as a per button cfg.
