### ISSUE TITLE
Add a generic `command button`

### ISSUE THREAD

**Issue by g0t4** [JetBrains/intellij-streamdeck-plugin#8]
It might help discoverability to have a generic button type that doesn't come tied to a specific action. 

I did find how to configure the ActionID to override a button's action, but that's not so intuitive, especially given many actions don't yet work.

Instead:
- Add generic button
- Set ActionID in button config
- Manually assign an icon:
  - Perhaps from an official JetBrains icon pack published to the StreamDeck store too?
- Or to be super fancy, the StreamDeck plugin could lookup the icon based on the ActionID! 
  - Of course allowing it to be changed too.

**Comment by beansoft** [comment]
@g0t4 Please try the latest version(not released yet) from https://github.com/JetBrains/intellij-streamdeck-plugin/blob/main/releases/com.jetbrains.ide.streamDeckPlugin, however only supports:
- Add generic button
- Set ActionID in button config
