### ISSUE TITLE
Missing documentation about how to get custom actions to work.

### ISSUE THREAD

**Issue by maxiangelo** [JetBrains/intellij-streamdeck-plugin#9]
How does the custom action actually need to be configured?
Also, I only found third-party lists of action IDs like the one here https://centic9.github.io/IntelliJ-Action-IDs/
I tried to get the MergeAllWindowsAction to work, I tried:
* MergeAllWindowsAction
* OpenProjectWindows.MergeAllWindowsAction

None of which worked.
The Logs for this from the stream deck plugin:
<img width="819" alt="image" src="https://github.com/JetBrains/intellij-streamdeck-plugin/assets/35735678/aa7b0bab-6275-48be-8f2e-55b637548ab3">

and the corresponding logs from IntelliJ:
```
2023-09-07 09:02:10,800 [ 300959]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2023-09-07 09:02:33,582 [ 323741]   INFO - STDOUT - 2023-09-07 09:02:33,581 stream deck req 
/api/action/OpenProjectWindows.MergeAllWindowsAction
2023-09-07 09:02:50,003 [ 340162]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files```

The logs look similar for both action IDs.
Also, the "ERR_CONNECTION_REFUSED" errors also happen when I trigger other functions from the stream deck like Project structure, but they work flawless.

**Comment by beansoft** [comment]
Thank you for your report. Not all action IDs are supported, but I'm still working on how to make them work.

> The Logs for this from the stream deck plugin:

Please ignore this first, it's caused by trying to communication to 10 running IDEs.

**Comment by JackyJetBrains** [comment]
This problem should be fixed in the newest version, please take a look at and help close it.

**Comment by maxiangelo** [comment]
Works wonderfully! Thanks
